### ISSUE TITLE
Add `wasm` support to `kmp-viewmodel-koin` and `kmp-viewmodel-koin-compose`

### ISSUE THREAD

**Issue by hoc081098** [hoc081098/kmp-viewmodel#148]
Blocked by https://github.com/InsertKoinIO/koin/issues/1634, https://github.com/InsertKoinIO/koin/issues/1885
Track: https://github.com/InsertKoinIO/koin/commits/3.6.0/

**Comment by hoangchungk53qx1** [comment]
🙏

**Comment by hoc081098** [comment]
> 🙏 

Pray 🙏
